export const revalidate = 60;

export default function TheoryPage() {
  return (
    <div className="min-h-screen pt-32 pb-20">
      <div className="max-w-7xl mx-auto px-6">
        {/* Header */}
        <div className="mb-16 text-center">
          <h1 className="font-space-grotesk text-7xl font-bold mb-6 tracking-tighter">
            The{" "}
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 via-white to-magenta-400">
              Theory
            </span>
          </h1>
          <p className="text-slate-400 text-xl max-w-3xl mx-auto leading-relaxed">
            Understanding the science and philosophy behind musically-tuned
            impulse responses
          </p>
        </div>

        {/* Main Content */}
        <div className="mb-20">
          {/* Video - Full Width */}
          <div className="max-w-4xl mx-auto mb-16">
            <div className="aspect-video bg-black rounded-xl border border-white/10 overflow-hidden relative group">
              <iframe
                width="100%"
                height="100%"
                src="https://www.youtube.com/embed/Lx9UfeujiqE"
                title="Theory Explanation"
                frameBorder="0"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                allowFullScreen
                className="w-full h-full"
              ></iframe>
            </div>
          </div>

          {/* Text Content - Flows Below */}
          <div className="max-w-4xl mx-auto space-y-12">
            <div>
              <h2 className="font-space-grotesk text-3xl font-bold mb-4 flex items-center gap-3">
                <span className="text-cyan-400">01</span>
                Harmonic Integration: Turning Reverb into Music
              </h2>
              <p className="text-slate-400 text-lg leading-relaxed mb-6">
                A core innovation of this methodology is that the reverb is an
                extension of the composition's tonality. The IRs are categorized
                into{" "}
                <span className="font-bold text-white">
                  12 tone folders (A to Bb)
                </span>
                , ensuring the reverb frequency response is perfectly aligned
                with the track's key, by balancing the energy of the dominant
                frequences.
              </p>

              <ul className="space-y-4 text-slate-400 text-lg">
                <li>
                  <span className="font-bold text-white">Chord Sculpting:</span>{" "}
                  Instead of a flat noise profile, the IR is generated by fading
                  out the fundamental frequencies of Major, Minor, Suspended,
                  and Diminished chords. <br />
                </li>
                <li>
                  <span className="font-bold text-white">
                    Root Frequency Attenuation:
                  </span>{" "}
                  To maintain the clarity of the mix, the frequencies of the
                  chords are algorithmically decreased in amplitude during the
                  creation of the IR. This keeps the reverb quitter on energy
                  dominant notes.
                </li>
              </ul>
            </div>

            <div>
              <h2 className="font-space-grotesk text-3xl font-bold mb-4 flex items-center gap-3">
                <span className="text-cyan-400">02</span>
                The Geometry of Decay
              </h2>
              <p className="text-slate-400 text-lg leading-relaxed mb-6">
                Dozens of different Decay Curves were created for the different
                needs of <span className="font-bold text-white">Music</span>
                <span className="italic"> (A Gift from the Gods)</span>.
              </p>
              <span className="font-bold text-white block mb-4">Examples:</span>

              <ul className="space-y-4 text-slate-400 text-lg">
                <li>
                  <span className="font-bold text-white">
                    The Astroid Curve:
                  </span>{" "}
                  A fast initial decay that transitions into a slow tail. It
                  occupies only 29.85% of the total square area, resulting in a
                  "tight" initial transient followed by an atmospheric bloom.
                </li>
                <li>
                  <span className="font-bold text-white">
                    The Gold 30 (Logarithmic):
                  </span>{" "}
                  Based on the Golden Ratio (φ) and a base-30 logarithmic
                  equation. This creates a slow, swelling decay at the start
                  with a rapid end, filling 39.85% of the area.
                </li>
                <li>
                  <span className="font-bold text-white">
                    The Witch of Agnesi:
                  </span>{" "}
                  Defined by a medium-slow decay at the beginning and a very
                  slow decay at the end, providing a "gentle" onset for vocals.
                </li>
                <li>
                  <span className="font-bold text-white">
                    Semicubical Parabola (SC044):
                  </span>{" "}
                  A medium-fast decay at the beginning with a very slow tail,
                  offering a balanced "all-purpose" response.
                </li>
              </ul>
            </div>

            <div>
              <h2 className="font-space-grotesk text-3xl font-bold mb-4 flex items-center gap-3">
                <span className="text-cyan-400">03</span>
                The Anti-Masking Principle & M/S Processing
              </h2>
              <p className="text-slate-400 text-lg leading-relaxed mb-6">
                To achieve a professional "three-dimensional" mix, the IRs
                utilize advanced building techniques to separate the focus of
                the reverb.
              </p>

              <ul className="space-y-4 text-slate-400 text-lg">
                <li>
                  <span className="font-bold text-white">M/S Building:</span>{" "}
                  Many impulses are processed using{" "}
                  <span className="font-bold text-white">
                    Mid-Side (M/S) synthesis
                  </span>
                  . This allows the user to have a different tonal weight or
                  decay curve on the "Sides" versus the "Center," preventing the
                  reverb from cluttering the phantom center where the dry lead
                  vocal or instrument usually sits.
                </li>
                <li>
                  <span className="font-bold text-white">
                    Frequency Constant Area (ISO):
                  </span>{" "}
                  Advanced collections use the "ISO" principle, where the
                  frequency energy of each decay band is kept constant, ensuring
                  that no specific frequency range "piles up" or masks others
                  during long decay times.
                </li>
              </ul>
            </div>

            {/* Key Principles Card */}
            <div className="p-6 bg-white/[0.02] border border-white/5 rounded-xl">
              <h4 className="text-xs font-space-mono text-cyan-400 uppercase tracking-widest mb-4">
                Key Principles
              </h4>
              <ul className="space-y-3 text-sm text-slate-400">
                <li className="flex items-start gap-3">
                  <span className="text-cyan-400 mt-1">•</span>
                  <span>
                    Geometric Decay Curves with Magic Numbers: Moving beyond
                    natural room physics, the IR utilizes mathematical equations
                    (Astroid, Logarithmic, Parabolic, etc.) to define contant
                    energy dissipation.
                  </span>
                </li>
                <li className="flex items-start gap-3">
                  <span className="text-cyan-400 mt-1">•</span>
                  <span>
                    9-Octave Extension: Every impulse is controlled across a
                    full 9-octave range.
                  </span>
                </li>
                <li className="flex items-start gap-3">
                  <span className="text-cyan-400 mt-1">•</span>
                  <span>
                    Fundamental Frequency Masking: To prevent "muddiness," the
                    chord notes frequencies are mathematically decreased
                    (curves) during IR creation.
                  </span>
                </li>
                <li className="flex items-start gap-3">
                  <span className="text-cyan-400 mt-1">•</span>
                  <span>
                    Harmonic Chord Structures: IRs are pre-sculpted to form
                    internal "chords" by decaying specific harmonic intervals
                    (frequencies).
                  </span>
                </li>
                <li className="flex items-start gap-3">
                  <span className="text-cyan-400 mt-1">•</span>
                  <span>
                    Dual-Perspective Spatiality: Impulses include Stereo and M/S
                    (Mid-Side) processing allowing independent decay behaviors
                    in the center, side and surround stereo fields.
                  </span>
                </li>
              </ul>
            </div>
          </div>
        </div>

        {/* Mathematical Foundation Section */}
        <div className="py-20 border-t border-white/5">
          <div className="text-center mb-12">
            <h2 className="font-space-grotesk text-4xl font-bold mb-4">
              Musical IR Foundation
            </h2>
            <p className="text-slate-400 text-lg max-w-2xl mx-auto">
              Our approach combines physics, mathematics, and music theory
            </p>
          </div>

          <div className="grid md:grid-cols-3 gap-8">
            {/* Card 1 */}

            <div className="glass-card p-8 rounded-xl text-center">
              <div className="text-3xl font-bold text-white mb-4 font-space-mono">
                λ = v / f
              </div>
              <h3 className="font-space-grotesk text-xl font-bold mb-2">
                Mathematical Curve
              </h3>
              <p className="text-slate-400 text-sm">
                Geometric Fall Curves (Astroid, Parabola, Gold 30) for precise
                RT60 energy ratios.
              </p>
            </div>

            {/* Card 2 */}
            <div className="glass-card p-8 rounded-xl text-center">
              <div className="text-3xl font-bold text-white mb-4 font-space-mono">
                ♬ ♩ ♪ ♫
              </div>
              <h3 className="font-space-grotesk text-xl font-bold mb-2">
                Tonal Alignment
              </h3>
              <p className="text-slate-400 text-sm">
                12-Tone Scale (A to Bb) with dedicated Major/Minor harmonic
                voicings.
              </p>
            </div>

            {/* Card 3 */}
            <div className="glass-card p-8 rounded-xl text-center">
              <div className="text-3xl font-bold text-white mb-4 font-space-mono">
                ∿ Ξ ∞ 〰
              </div>
              <h3 className="font-space-grotesk text-xl font-bold mb-2">
                Spectral Range
              </h3>
              <p className="text-slate-400 text-sm">
                Full 9-Octave Extension, for consistent harmonic support across
                the entire audible spectrum.
              </p>
            </div>

            {/* Card 4 */}
            <div className="glass-card p-8 rounded-xl text-center">
              <div className="text-3xl font-bold text-white mb-4 font-space-mono">
                ⌬ ⫗ ⬡
              </div>
              <h3 className="font-space-grotesk text-xl font-bold mb-2">
                Anti-Masking EQ
              </h3>
              <p className="text-slate-400 text-sm">
                Fundamental Frequency Attenuation to preserve dry signal clarity
                and eliminate low-mid buildup
              </p>
            </div>

            {/* Card 5 */}
            <div className="glass-card p-8 rounded-xl text-center">
              <div className="text-3xl font-bold text-white mb-4 font-space-mono">
                ⟡ ◎ ▽
              </div>
              <h3 className="font-space-grotesk text-xl font-bold mb-2">
                Harmonic Profile
              </h3>
              <p className="text-slate-400 text-sm">
                Internal 3th and 5th-interval harmonic sculpting for
                "Chord-based" resonant tails.
              </p>
            </div>

            {/* Card 6 */}
            <div className="glass-card p-8 rounded-xl text-center">
              <div className="text-3xl font-bold text-white mb-4 font-space-mono">
                ◱ ⚯ ◲
              </div>
              <h3 className="font-space-grotesk text-xl font-bold mb-2">
                Stereo Architecture
              </h3>
              <p className="text-slate-400 text-sm">
                M/S (Mid-Side) Dual-Building for independent center-focus and
                side-field width.
              </p>
            </div>
          </div>
        </div>

        {/* CTA Section */}
        <div className="mt-20 text-center">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full border border-cyan-500/30 bg-cyan-500/5 text-cyan-400 text-[10px] uppercase tracking-widest mb-6">
            <span className="relative flex h-2 w-2">
              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-cyan-400 opacity-75"></span>
              <span className="relative inline-flex rounded-full h-2 w-2 bg-cyan-500"></span>
            </span>
            Ready to Experience the Difference?
          </div>
          <h2 className="font-space-grotesk text-5xl font-bold mb-6">
            Explore Our Collections
          </h2>
          <p className="text-slate-400 text-lg mb-8 max-w-2xl mx-auto">
            Each collection represents a different approach to harmonic sequence
            control of sources, from natural acoustic elements to algorithmic
            noise profiles. All IRs are harmonically tuned to ensure your reverb
            is not just heard, but felt as a musical extension of your sound.
          </p>
          <a
            href="/collections"
            className="inline-block bg-cyan-500 hover:bg-cyan-400 text-black px-8 py-4 rounded-full font-bold uppercase text-sm transition-all"
          >
            Browse Collections
          </a>
        </div>
      </div>
    </div>
  );
}
